Repository sensebox/openSenseMap-API, pull requests merged in 2023-09, with the labels that each got.

#801 Update restify to support node 18
  Dockerfile
  packages/api/package.json
  packages/models/src/measurement/decoding/validators.js
  tests/tests-Dockerfile
  yarn.lock
Labels: security

#577 (feat): new route for querying tags
  packages/api/lib/controllers/boxesController.js
  packages/api/lib/routes.js
  tests/data/valid_sensebox.js
  tests/tests/005-create-boxes-test.js
Labels: enhancement, feature

#822 (feat): add description to `postNewBox` route
  packages/api/lib/controllers/boxesController.js
  packages/models/src/box/box.js
Labels: feature request
